# Generated by Django 4.1.4 on 2022-12-18 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebGraphique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='file',
            field=models.FileField(upload_to='files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
