# Generated by Django 4.1.4 on 2022-12-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebGraphique', '0002_alter_csvfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
