# Generated by Django 4.1.4 on 2023-01-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebGraphique', '0003_alter_csvfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVFile',
        ),
    ]
