---
name: Pull Request
about: Template de pull request pour les contributions au projet
title: ''
labels: ''
assignees: ''

---

## Description

Veuillez fournir une description de la modification apportée par cette pull request.

## Motivation

Pourquoi avez-vous effectué cette modification? Quel problème cela résout-il?

## Commentaires

Avez-vous des commentaires supplémentaires sur cette modification?

## Vérification

- [ ] J'ai vérifié que ma modification ne provoque pas de régression
- [ ] J'ai testé ma modification en local
- [ ] J'ai mis à jour la documentation, le cas échéant

## Références

Avez-vous fait référence à un ticket de suivi ou à une autre pull request? Si oui, veuillez les inclure ici.
