---
name: Bug
about: Template pour signaler un bug dans le projet 
title: ''
labels: bug
assignees: ''

---

## Description

Veuillez fournir une description détaillée du bug que vous avez rencontré.

## Étapes pour reproduire

1. Ouvrez votre terminal
2. Tapez la commande '...'
3. Voir l'erreur

## Comportement attendu

Veuillez décrire ce à quoi vous vous attendiez de voir.

## Comportement observé

Veuillez décrire ce que vous avez observé à la place.

## Captures d'écran

Si applicable, ajoutez des captures d'écran pour aider à expliquer votre problème.

## Informations supplémentaires

Veuillez fournir toute autre information qui pourrait être utile pour reproduire et résoudre ce bug.

## Références

Avez-vous fait référence à un ticket de suivi ou à une autre issue? Si oui, veuillez les inclure ici.
